openapi: 3.0.3
info:
  title: MindGarden API
  version: '0.1.0'
  description: |
    OpenAPI specification per gli endpoint core di MindGarden: auth, uploads, checkins, gardens, plants, insights, export e settings.
servers:
  - url: https://api.mindgarden.example.com/v1
    description: Production server (example)
  - url: https://staging.api.mindgarden.example.com/v1
    description: Staging
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
      example:
        error:
          code: invalid_request
          message: Missing required field `text`

    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        createdAt:
          type: string
          format: date-time
      required: [id]

    Tokens:
      type: object
      properties:
        access:
          type: string
        refresh:
          type: string

    AuthRegisterRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required: [email, password]

    AuthResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        tokens:
          $ref: '#/components/schemas/Tokens'

    SignedUrlRequest:
      type: object
      properties:
        userId:
          type: string
        contentType:
          type: string
        lengthSeconds:
          type: number
      required: [userId, contentType]

    SignedUrlResponse:
      type: object
      properties:
        uploadUrl:
          type: string
        objectKey:
          type: string

    CheckInCreateText:
      type: object
      properties:
        userId:
          type: string
        timestamp:
          type: string
          format: date-time
        text:
          type: string
        emotionHint:
          type: string
        intensity:
          type: number
        tags:
          type: array
          items:
            type: string
      required: [userId]

    CheckInCreateAudio:
      type: object
      properties:
        userId:
          type: string
        timestamp:
          type: string
          format: date-time
        audioObjectKey:
          type: string
        emotionHint:
          type: string
      required: [userId, audioObjectKey]

    CheckIn:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
        createdAt:
          type: string
          format: date-time
        timestamp:
          type: string
          format: date-time
        text:
          type: string
        sttText:
          type: string
        audioObjectKey:
          type: string
        emotionLabel:
          type: string
        sentimentScore:
          type: number
        intensity:
          type: number
        tags:
          type: array
          items:
            type: string
        embeddingsId:
          type: string
        status:
          type: string
      example:
        id: check-uuid-1234
        userId: user-uuid-1234
        createdAt: '2025-11-19T10:00:00Z'
        timestamp: '2025-11-19T10:00:00Z'
        text: 'Mi sento ansioso per domani'
        sttText: 'Mi sento ansioso per domani'
        emotionLabel: 'ansia'
        sentimentScore: -0.4
        intensity: 0.7
        status: 'complete'

    PlantInstance:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        checkinId:
          type: string
        archetype:
          type: string
        params:
          type: object
        position:
          type: object
        styleSkin:
          type: string
        health:
          type: number
        growthProgress:
          type: number
        createdAt:
          type: string
          format: date-time

    Garden:
      type: object
      properties:
        gardenId:
          type: string
        userId:
          type: string
        createdAt:
          type: string
          format: date-time
        plants:
          type: array
          items:
            $ref: '#/components/schemas/PlantInstance'
        aggregate:
          type: object

    ActionRequest:
      type: object
      properties:
        userId:
          type: string
        action:
          type: string
          description: 'water | meditate | journal | prune'
        metadata:
          type: object
      required: [userId, action]

    Insight:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        createdAt:
          type: string
          format: date-time
        text:
          type: string
        insightType:
          type: string
        sourceCheckins:
          type: array
          items:
            type: string

paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRegisterRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required: [email, password]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Unauthorized

  /auth/refresh:
    post:
      summary: Refresh access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
              required: [refreshToken]
      responses:
        '200':
          description: New tokens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tokens'

  /uploads/signed-url:
    post:
      summary: Request signed URL for file upload
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignedUrlRequest'
      responses:
        '200':
          description: Signed URL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignedUrlResponse'

  /checkins:
    post:
      summary: Create a check-in (text or audio)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/CheckInCreateText'
                - $ref: '#/components/schemas/CheckInCreateAudio'
            examples:
              text-example:
                value:
                  userId: user-uuid-1234
                  text: "Mi sento ansioso per domani"
              audio-example:
                value:
                  userId: user-uuid-1234
                  audioObjectKey: audios/user-uuid-abc123.wav
      responses:
        '201':
          description: Check-in accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  checkin:
                    $ref: '#/components/schemas/CheckIn'
        '400':
          description: Bad request

    get:
      summary: List check-ins (filterable)
      security:
        - bearerAuth: []
      parameters:
        - name: from
          in: query
          schema:
            type: string
            format: date-time
        - name: to
          in: query
          schema:
            type: string
            format: date-time
        - name: emotion
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
      responses:
        '200':
          description: List of check-ins
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CheckIn'

  /checkins/{id}:
    get:
      summary: Get check-in detail
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Check-in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckIn'
        '404':
          description: Not found

  /gardens/me:
    get:
      summary: Get current user's garden snapshot
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Garden snapshot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Garden'

  /plants/{plantId}:
    get:
      summary: Get plant instance detail
      security:
        - bearerAuth: []
      parameters:
        - name: plantId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Plant instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlantInstance'

  /plants/{plantId}/actions:
    post:
      summary: Perform care action on a plant
      security:
        - bearerAuth: []
      parameters:
        - name: plantId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActionRequest'
      responses:
        '200':
          description: Action accepted and plant updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlantInstance'

  /insights:
    get:
      summary: List recent insights from Garden Keeper
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Insights
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Insight'

  /insights/generate:
    post:
      summary: Request on-demand insight generation
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                fromDate:
                  type: string
                  format: date-time
                toDate:
                  type: string
                  format: date-time
                checkinIds:
                  type: array
                  items:
                    type: string
      responses:
        '202':
          description: Insight generation queued
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobId:
                    type: string

  /export:
    post:
      summary: Request export of user data (GDPR)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                format:
                  type: string
                  enum: [json, zip]
      responses:
        '202':
          description: Export queued

  /data:
    delete:
      summary: Delete all user data (GDPR delete)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
      responses:
        '202':
          description: Deletion queued

  /settings/me:
    get:
      summary: Get current user's settings
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Settings
          content:
            application/json:
              schema:
                type: object
                properties:
                  processingMode:
                    type: string
                    enum: [cloud, on-device]
                  audioRetentionDays:
                    type: integer
                  shareAnonymized:
                    type: boolean

    patch:
      summary: Update current user's settings
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                processingMode:
                  type: string
                  enum: [cloud, on-device]
                audioRetentionDays:
                  type: integer
                shareAnonymized:
                  type: boolean
      responses:
        '200':
          description: Updated
