import React from 'react';
import { BrowserRouter as Router, Routes, Route, Navigate } from 'react-router-dom';
import { AuthProvider, useAuth } from './features/auth/useAuth';
import { ThemeProvider } from './core/theme';
import { ToastProvider } from './shared/ToastContainer';
import LoginForm from './features/auth/LoginForm';
import GardenViewer from './features/garden/GardenViewer';
import CheckInForm from './features/checkin/CheckInForm';
import ARPreview from './features/garden/ARPreview';
import AnalyticsDashboard from './features/analytics/AnalyticsDashboard';
import ChatInterface from './features/chatbot/ChatInterface';
import Navigation from './shared/Navigation';
